---
- name: OSPF ACTIVATION
  hosts: R1
  gather_facts: false
  connection: local
 
  tasks:
   - name: ACTIVATE OSPF USING NETWORK STATEMENTS
     ios_config:
       parents: "router ospf 1"
       lines:
         - router-id 1.1.1.1
         - network 192.168.10.10 0.0.0.255 area 0
         - network 10.10.1.0 0.0.0.3 area 0

   - name: ACTIVATE OSPF FAST ETHERNET 0/0
     ios_config:
       parents: "interface FastEthernet0/0"
       lines:
         - ip ospf 1 area 0     
 
   - name: ACTIVATE OSPF in SERIAL 0/0
     ios_config:
       parents: "interface Serial0/0"
       lines:
         - ip ospf 1 area 0  
 


  
